name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: ''
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_skyline: yes
          plugin_skyline_year: 0            # Set to 0 to display current year
          plugin_skyline_frames: 60         # Use 60 frames (half-loop)
          plugin_skyline_quality: 0.5       # Set image quality
          plugin_skyline_compatibility: yes # Support additional browsers (⚠️ increases file size and reduce optimization)
